### ISSUE TITLE
html razmetkada to'g'riroq usuldan foydalanish mumkin

### ISSUE THREAD

**Issue by Javohirshakh** [anwarbek/namanganliklar-24#15]
html razmetkada div ichiga span qo'ygansiz. Lekin divsiz spanning o'zini qo'yib ishlatishingiz ham mumkin edi
![image](https://user-images.githubusercontent.com/77332200/135614737-8d3379e7-071d-4fea-856a-932c81f6c48d.png)

**Comment by akhilpamwani** [comment]
I can do it for you
